#CI
on:
  push:
    branches: [ "main" ]
    # paths:
    #  - "test_case/tc01.login.js"
     #- "test_case/**/*.js" / klo ini semua file.js yg ada di dalam folder test_case
  pull_request:
    branches: [ "main" ]
    # paths: 
    #     - "test_case/tc01.login.js"
        #- "test_case/**/*.js" / klo ini semua file.js yg ada di dalam folder test_case

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Run Mocha tests
      - name: Run Mocha tests
        run: npm run test_02

    
      - name: Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/

#CD
#   deploy:
#         needs: run_test
#         runs-on: ubuntu-latest
    
#         steps:
#         - name: Checkout code
#           uses: actions/checkout@v4
    
#         - name: Setup Node.js
#           uses: actions/setup-node@v4
#           with:
#             node-version: 22
    
#         - name: Install dependencies
#           run: npm ci
    
#         - name: Deploy Application
#           uses: peaceiris/actions-gh-pages@v3
#           with:
#             github_token: ${{ secrets.GITHUB_TOKEN }}
#             publish_dir: ./mochawesome-report
#             destination_dir: 'report'   